
APP_NAME_MAP = {
    "com.kakao.talk": "카카오톡",
    "com.instagram.android": "인스타그램",
    "com.twitter.android": "트위터",
    "com.discord": "디스코드",
    "com.google.android.youtube": "유튜브",
    "com.everytime.v2": "에브리타임",
    "com.geode.launcher": "지오메트리 대시",
    "gg.dak.bser": "이터널 리턴",
    "com.robtopx.geometryjump": "지오메트리 점프",
    "com.riotgames.league.teamfighttactics": "TFT",
    "com.kurogame.wutheringwaves.global": "명조",
    "com.spotify.music": "스포티파이",
    "com.netflix.mediaclient": "넷플릭스",
    "com.nhn.android.webtoon": "네이버 웹툰",
    "com.android.chrome": "크롬",
    "notion.id": "노션",
    "com.samsung.android.app.notes": "삼성 노트",
    "com.coupang.mobile": "쿠팡",
    "com.nhn.android.nmap": "네이버 지도",
    "com.samsung.android.dialer": "알람",
    "com.samsung.android.incallui": "통화",
    "com.sec.android.app.camera": "카메라",
    "com.sec.android.gallery3d": "갤러리",
    "com.sec.android.app.launcher": "홈",
    "com.android.settings": "설정",
    "com.samsung.android.easysetup": "에이지 셋업",
    "com.kakaopay.app": "카카오페이"
}